version: 2.0
jobs:
  "MyTaxiTest":
    docker:
      - image: circleci/openjdk:stretch
    build:
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - store_test_results:
          path: test-output
      - store_artifacts:
          path: /test-output/test-report.html




workflows:
  version: 2
  build-workflow:
    jobs:
      - "MyTaxiTest"