version: 2.0
jobs:
  "MyTaxiTest":
    docker:
      - image: circleci/openjdk:stretch
    build:
      working_directory: ~/backendTest/myTaxi
    steps:
      - run: mvn dependency:go-offline
      - run: mvn test
      - run: echo "hello world"

workflows:
  version: 2
  build-workflow:
    jobs:
      - "MyTaxiTest"