version: 2.0
jobs:
  "MyTaxiTest":
    steps:
      - checkout
      - run: mvn test
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - "MyTaxiTest"